# proxy config
[proxy]
# You can add your proxies here
# Support proxy protocol: http/https, socks5, shadowsocks, trojan

# Example:
# Http/Https: [http/https],[name/alias],[server],[port],traff=[tcp/udp/both],mux=[no/smux]
# Socks5: [socks5],[name/alias],[server],[port],[username],[password],traff=[tcp/udp/both],mux=[no/mux]
# Shadowsocks: [shadow],[name/alias],[server],[port],[cipher],[password],traff=[tcp/udp/both],mux=[no/mux]
# Trojan: [trojan],[name/alias],[server],[port],[password],[sni],traff=[tcp/udp/both],mux=[no/mux]
proxies = [
    # "trojan,example1,siuu.com,8080,xxxxxxx,siuu.com,traff=tcp,mux=smux",
]


alias = [
    # "name:[ALADASD, adasdaw, sadasd, asdawdq, asdawd]",
]


# route table config
[route]

# First priority is excat match
# Second priority is wildcard match
# Third priority is geo match
# If there is no matching rule, it will not use any proxies

# If you want to use the default proxy,you can set the proxy name to default.
# You can set the default proxy as you like
# eg : [type],[xxxxx],default

rules = [
    # "exact,example1,example2",
    # "wildcard,example1,example2",
    # "geo,example1,example2",
]