
# Log configuration
[log]

# - path: log file path, using '~' means the home directory of user
# - level.system: log level of system, including error, warn, info, debug
# - level.proxy: log level of proxy, including  error, warn, info, debug
path = '~/.siuu/log/'
level.system = 'DEBUG'
level.proxy = 'INFO'



# Server configuration
[server]

# - port: the main port on which the server listens for control command connections
port = 17777



# listens for pprof ,the port is 6060
[server.pprof]
enable = false
port = 6060


# proxy configuration
[server.proxy]

# - model: proxy model, including system, tun. The default value is system
# - tables: routing tables configuration file path
mode = "system"
tables = [
    "/Users/mazhj/Documents/workspaces/projects/siuu/conf/proxies.toml",
]


# os http proxy service configuration
# if the tun mode is enabled, the following configuration regarding the os proxy will be ignored.
[server.proxy.http]

# - http.enable: if open the http proxy
# - http.port: the port dedicated for HTTP proxy connections
enable = true
port = 18888

# os socks proxy service configuration
[server.proxy.socks]

# - socks.enable: if open the socks proxy
# - socks.port: the port dedicated for SOCKS5 proxy connections
enable = true
port = 19999